# Permalinks
#
permalink:           pretty
markdown:            kramdown

# Setup
title:               Cascadia Airbnb
tagline:             'Analysis of AirBnb listings in Portland, Seattle, and Vancouver.'
description:         'Wrangling, analyzing and modeling Airbnb data to explore answers to questions about listing prices and guest satisfaction.'
url:                 https://rmwenzel.com
baseurl:             /cascadia_airbnb

# About/contact
author:
  name:              Ryan Wenzel
  url:               https://rmwenzel.com
  email:             rmwenzel@uw.edu

kramdown:
  parse_block_html: true

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-katex

